In [45]:
import csv
import numpy as np

ROW_CNT = 1000
COL_CNT = 12

X = np.zeros((ROW_CNT, COL_CNT))

with open('raw_data.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for idx, row in enumerate(csv_reader):
        if row[0] != '':
            X[idx, :] = list(map(lambda x: int(x), row[:]))

12000


In [65]:
KNN_ITER = 10
CLUSTER_CNT = 4

def min_dist(data_point, centroids):
    min_l2_dist = np.sum((data_point - centroids[0])**2)
    closest_centroid = 0
    
    for i in range(1, centroids.shape[0]):
        if np.sum((data_point - centroids[i])**2) < min_l2_dist:
            min_l2_dist = np.sum((data_point - centroids[i])**2)
            closest_centroid = i
    
    return closest_centroid

def centr_fit(centroid, X, ):
    


centroids = np.zeros((CLUSTER_CNT, COL_CNT))
best_centroids = np.zeros((CLUSTER_CNT, COL_CNT))
classes = np.zeros((ROW_CNT, 1))

for i in range(KNN_ITER):
    print("Iteration", i)
    
    idx = np.random.randint(ROW_CNT, size=CLUSTER_CNT)
    print(idx)
    centroids = X[idx, :]
    
    const_clusters = False
    while not const_clusters:
        const_clusters = True
        for c in range(classes.shape[0]):
            new_class = min_dist(X[c], centroids)
            if new_class != classes[c]:
                const_clusters = False
            classes[c] = new_class
            
        new_centroids = np.zeros((CLUSTER_CNT, COL_CNT))
        for j in range(centroids.shape[0]):
            class_elem_cnt = 0
            for c in range(classes.shape[0]):
                if classes[c] == j:
                    class_elem_cnt += 1
                    new_centroids[j] += X[c]
            
            if class_elem_cnt != 0:
                new_centroids[j] = new_centroids[j] / class_elem_cnt
            centroids[j] = new_centroids[j]

print(centroids)

Iteration 0
[125 928  52  76]
Iteration 1
[884 695 440 124]
Iteration 2
[ 60 195 274 926]
Iteration 3
[361 314 604 159]
Iteration 4
[681  91 583 693]
Iteration 5
[ 46 648 750 983]
Iteration 6
[181 166  58 703]
Iteration 7
[155 439 815 329]
Iteration 8
[500 983 506 213]
Iteration 9
[805 376 788 682]
[[7.47126437e-01 1.00000000e+00 1.13793103e+00 5.15747126e+01
  7.47126437e-01 3.98850575e+00 6.86091954e+01 8.74712644e+00
  8.23310345e+02 1.14942529e-02 1.12643678e+00 1.02298851e+00]
 [8.75739645e-01 6.86390533e-01 1.35502959e+00 5.05384615e+01
  8.69822485e-01 3.39644970e+00 4.78402367e+01 2.09526627e+01
  5.74082840e+02 5.79881657e-01 4.19526627e+00 2.76331361e+00]
 [4.46721311e-01 8.03278689e-01 1.51229508e+00 3.81844262e+01
  3.97540984e-01 1.98360656e+00 3.47008197e+01 2.60327869e+01
  4.16409836e+02 4.13934426e-01 4.29508197e+00 3.27459016e+00]
 [7.96000000e-01 5.02000000e-01 2.82000000e-01 5.19980000e+01
  5.02000000e-01 1.01200000e+00 1.68820000e+01 2.46640000e+01
  2.02584000e+0

In [66]:
with open('kNN-out.csv', mode='w') as csv_file:
    csv_writer = csv.writer(csv_file, delimiter=',')
    for idx in range(centroids.shape[0]):
        csv_writer.writerow(centroids[idx])

In [77]:
with open('clustered-data.csv', mode='w') as csv_file:
    csv_writer = csv.writer(csv_file, delimiter=',')
    for idx in range(CLUSTER_CNT):
        for c in range(classes.shape[0]):
            if classes[c] == idx:
                csv_writer.writerow(X[c].tolist() + [idx])